name: u3_tarea1

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # Ejecuta el workflow una vez al d√≠a a la medianoche UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Validar Makefile
        run: |
          cd $GITHUB_WORKSPACE/u3_tarea0
          chmod +x setup.sh 
          ./setup.sh
          make help
          make clean
          make post 
          make build
